-- Seed 10 PH listings + addresses in one go (idempotent if IDs unchanged)

BEGIN;

WITH raw AS (
  SELECT '
  [
    {
      "seed_key": 1,
      "id": "LSEED0001",
      "status": "active",
      "intent": "sale",
      "property_type": "condo",
      "price_amount": 12500000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": 2,
      "baths": 2,
      "floor_area_sqm": 72,
      "lot_area_sqm": null,
      "year_built": 2018,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0001",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"parking_slots":1, "amenities":["pool","gym"], "furnished": true},
      "address": {
        "seed_key": 1,
        "country_code": "PH",
        "region": "NCR",
        "province": "Metro Manila",
        "city_municipality": "Taguig",
        "barangay": "Fort Bonifacio",
        "subdivision": "BGC",
        "street_address": "26th St",
        "postal_code": "1634",
        "formatted_address": "26th St, BGC, Fort Bonifacio, Taguig, 1634",
        "location": {"lat": 14.5491, "lng": 121.0463}
      },
      "location": {"lat": 14.5491, "lng": 121.0463}
    },
    {
      "seed_key": 2,
      "id": "LSEED0002",
      "status": "active",
      "intent": "rent",
      "property_type": "condo",
      "price_amount": 65000,
      "price_currency": "PHP",
      "price_frequency": "monthly",
      "beds": 1,
      "baths": 1,
      "floor_area_sqm": 40,
      "lot_area_sqm": null,
      "year_built": 2020,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0002",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"parking_slots":0, "amenities":["gym"]},
      "address": {
        "seed_key": 2,
        "country_code": "PH",
        "region": "NCR",
        "province": "Metro Manila",
        "city_municipality": "Makati",
        "barangay": "Bel-Air",
        "subdivision": null,
        "street_address": "Makati Ave",
        "postal_code": "1227",
        "formatted_address": "Makati Ave, Bel-Air, Makati, 1227",
        "location": {"lat": 14.5546, "lng": 121.0244}
      },
      "location": {"lat": 14.5546, "lng": 121.0244}
    },
    {
      "seed_key": 3,
      "id": "LSEED0003",
      "status": "active",
      "intent": "sale",
      "property_type": "house",
      "price_amount": 18500000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": 4,
      "baths": 3,
      "floor_area_sqm": 220,
      "lot_area_sqm": 180,
      "year_built": 2010,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0003",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"carport":2, "maid_room": true},
      "address": {
        "seed_key": 3,
        "country_code": "PH",
        "region": "NCR",
        "province": "Metro Manila",
        "city_municipality": "Quezon City",
        "barangay": "Loyola Heights",
        "subdivision": null,
        "street_address": "Katipunan Ave",
        "postal_code": "1108",
        "formatted_address": "Katipunan Ave, Loyola Heights, QC 1108",
        "location": {"lat": 14.6362, "lng": 121.0769}
      },
      "location": {"lat": 14.6362, "lng": 121.0769}
    },
    {
      "seed_key": 4,
      "id": "LSEED0004",
      "status": "active",
      "intent": "sale",
      "property_type": "townhouse",
      "price_amount": 14500000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": 3,
      "baths": 2,
      "floor_area_sqm": 140,
      "lot_area_sqm": 80,
      "year_built": 2015,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0004",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"gated": true},
      "address": {
        "seed_key": 4,
        "country_code": "PH",
        "region": "NCR",
        "province": "Metro Manila",
        "city_municipality": "Manila",
        "barangay": "Ermita",
        "subdivision": null,
        "street_address": "Roxas Blvd",
        "postal_code": "1000",
        "formatted_address": "Roxas Blvd, Ermita, Manila 1000",
        "location": {"lat": 14.5790, "lng": 120.9800}
      },
      "location": {"lat": 14.5790, "lng": 120.9800}
    },
    {
      "seed_key": 5,
      "id": "LSEED0005",
      "status": "active",
      "intent": "sale",
      "property_type": "house",
      "price_amount": 12500000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": 3,
      "baths": 2,
      "floor_area_sqm": 160,
      "lot_area_sqm": 200,
      "year_built": 2012,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0005",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"garage":1},
      "address": {
        "seed_key": 5,
        "country_code": "PH",
        "region": "Region VII",
        "province": "Cebu",
        "city_municipality": "Cebu City",
        "barangay": "Lahug",
        "subdivision": null,
        "street_address": "Salinas Dr",
        "postal_code": "6000",
        "formatted_address": "Salinas Dr, Lahug, Cebu City 6000",
        "location": {"lat": 10.3320, "lng": 123.8980}
      },
      "location": {"lat": 10.3320, "lng": 123.8980}
    },
    {
      "seed_key": 6,
      "id": "LSEED0006",
      "status": "active",
      "intent": "rent",
      "property_type": "house",
      "price_amount": 38000,
      "price_currency": "PHP",
      "price_frequency": "monthly",
      "beds": 3,
      "baths": 2,
      "floor_area_sqm": 120,
      "lot_area_sqm": 150,
      "year_built": 2016,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0006",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"pet_friendly": true},
      "address": {
        "seed_key": 6,
        "country_code": "PH",
        "region": "Region XI",
        "province": "Davao del Sur",
        "city_municipality": "Davao City",
        "barangay": "Poblacion",
        "subdivision": null,
        "street_address": "JP Laurel Ave",
        "postal_code": "8000",
        "formatted_address": "JP Laurel Ave, Poblacion, Davao City 8000",
        "location": {"lat": 7.0731, "lng": 125.6128}
      },
      "location": {"lat": 7.0731, "lng": 125.6128}
    },
    {
      "seed_key": 7,
      "id": "LSEED0007",
      "status": "active",
      "intent": "sale",
      "property_type": "lot",
      "price_amount": 6800000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": null,
      "baths": null,
      "floor_area_sqm": null,
      "lot_area_sqm": 350,
      "year_built": null,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0007",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"corner_lot": true},
      "address": {
        "seed_key": 7,
        "country_code": "PH",
        "region": "CAR",
        "province": "Benguet",
        "city_municipality": "Baguio",
        "barangay": "Greenwater",
        "subdivision": null,
        "street_address": "Loakan Rd",
        "postal_code": "2600",
        "formatted_address": "Loakan Rd, Greenwater, Baguio 2600",
        "location": {"lat": 16.4023, "lng": 120.5960}
      },
      "location": {"lat": 16.4023, "lng": 120.5960}
    },
    {
      "seed_key": 8,
      "id": "LSEED0008",
      "status": "active",
      "intent": "sale",
      "property_type": "house",
      "price_amount": 9200000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": 3,
      "baths": 2,
      "floor_area_sqm": 130,
      "lot_area_sqm": 180,
      "year_built": 2014,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0008",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"garden": true},
      "address": {
        "seed_key": 8,
        "country_code": "PH",
        "region": "Region VI",
        "province": "Iloilo",
        "city_municipality": "Iloilo City",
        "barangay": "Jaro",
        "subdivision": null,
        "street_address": "E Lopez St",
        "postal_code": "5000",
        "formatted_address": "E Lopez St, Jaro, Iloilo City 5000",
        "location": {"lat": 10.7202, "lng": 122.5621}
      },
      "location": {"lat": 10.7202, "lng": 122.5621}
    },
    {
      "seed_key": 9,
      "id": "LSEED0009",
      "status": "active",
      "intent": "rent",
      "property_type": "house",
      "price_amount": 28000,
      "price_currency": "PHP",
      "price_frequency": "monthly",
      "beds": 2,
      "baths": 1,
      "floor_area_sqm": 85,
      "lot_area_sqm": 120,
      "year_built": 2008,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0009",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"near_mall": true},
      "address": {
        "seed_key": 9,
        "country_code": "PH",
        "region": "Region VI",
        "province": "Negros Occidental",
        "city_municipality": "Bacolod",
        "barangay": "Mandalagan",
        "subdivision": null,
        "street_address": "Lacson St",
        "postal_code": "6100",
        "formatted_address": "Lacson St, Mandalagan, Bacolod 6100",
        "location": {"lat": 10.6765, "lng": 122.9509}
      },
      "location": {"lat": 10.6765, "lng": 122.9509}
    },
    {
      "seed_key": 10,
      "id": "LSEED0010",
      "status": "active",
      "intent": "sale",
      "property_type": "land",
      "price_amount": 5200000,
      "price_currency": "PHP",
      "price_frequency": "one_time",
      "beds": null,
      "baths": null,
      "floor_area_sqm": null,
      "lot_area_sqm": 500,
      "year_built": null,
      "h3_res9": null,
      "agent_id": null,
      "owner_id": null,
      "source": "manual",
      "external_source_id": "SEED-0010",
      "published_at": "2025-08-26T08:00:00Z",
      "expires_at": null,
      "created_at": "2025-08-26T08:00:00Z",
      "updated_at": "2025-08-26T08:00:00Z",
      "version": 1,
      "attrs": {"road_frontage_m": 15},
      "address": {
        "seed_key": 10,
        "country_code": "PH",
        "region": "Region X",
        "province": "Misamis Oriental",
        "city_municipality": "Cagayan de Oro",
        "barangay": "Carmen",
        "subdivision": null,
        "street_address": "Vamenta Blvd",
        "postal_code": "9000",
        "formatted_address": "Vamenta Blvd, Carmen, CDO 9000",
        "location": {"lat": 8.4779, "lng": 124.6319}
      },
      "location": {"lat": 8.4779, "lng": 124.6319}
    }
  ]
  '::json AS j
),
listings AS (
  SELECT * FROM json_to_recordset((SELECT j FROM raw)) AS (
    seed_key INT,
    id TEXT,
    status TEXT,
    intent TEXT,
    property_type TEXT,
    price_amount NUMERIC,
    price_currency TEXT,
    price_frequency TEXT,
    beds NUMERIC,
    baths NUMERIC,
    floor_area_sqm NUMERIC,
    lot_area_sqm NUMERIC,
    year_built INT,
    h3_res9 TEXT,
    agent_id TEXT,
    owner_id TEXT,
    source TEXT,
    external_source_id TEXT,
    published_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    version INT,
    attrs JSONB,
    address JSON
  )
),
addr_rows AS (
  SELECT
    (address->>'seed_key')::int AS seed_key,
    'ASEED' || lpad((address->>'seed_key'),4,'0') AS id,
    address->>'country_code' AS country_code,
    address->>'region' AS region,
    address->>'province' AS province,
    address->>'city_municipality' AS city_municipality,
    address->>'barangay' AS barangay,
    address->>'subdivision' AS subdivision,
    address->>'street_address' AS street_address,
    address->>'postal_code' AS postal_code,
    address->>'formatted_address' AS formatted_address,
    (address->'location'->>'lat')::double precision AS lat,
    (address->'location'->>'lng')::double precision AS lng
  FROM listings
),
ins_addr AS (
  INSERT INTO address (
    id, country_code, region, province, city_municipality, barangay, subdivision,
    street_address, postal_code, formatted_address, location
  )
  SELECT
    id, country_code, region, province, city_municipality, barangay, subdivision,
    street_address, postal_code, formatted_address,
    ST_SetSRID(ST_MakePoint(lng, lat),4326)::geography
  FROM addr_rows
  ON CONFLICT (id) DO NOTHING
  RETURNING id
),
final_insert AS (
  INSERT INTO listing (
    id, status, intent, property_type, price_amount, price_currency, price_frequency,
    beds, baths, floor_area_sqm, lot_area_sqm, year_built, address_id, location,
    h3_res9, agent_id, owner_id, source, external_source_id, published_at, expires_at,
    created_at, updated_at, version, attrs
  )
  SELECT
    l.id,
    l.status::listing_status,
    l.intent::listing_intent,
    l.property_type::property_type,
    l.price_amount, l.price_currency, l.price_frequency::price_frequency,
    l.beds, l.baths, l.floor_area_sqm, l.lot_area_sqm, l.year_built,
    'ASEED' || lpad(l.seed_key::text,4,'0') AS address_id,
    ST_SetSRID(ST_MakePoint(
      (l.address->'location'->>'lng')::double precision,
      (l.address->'location'->>'lat')::double precision
    ),4326)::geography,
    l.h3_res9, l.agent_id, l.owner_id, l.source, l.external_source_id,
    l.published_at, l.expires_at, l.created_at, l.updated_at, l.version,
    COALESCE(l.attrs, '{}'::jsonb)
  FROM listings l
  ON CONFLICT (id) DO NOTHING
  RETURNING id
)
SELECT COUNT(*) AS rows_inserted FROM final_insert;

COMMIT;
